// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/568ec4378d010bb901a61bd9686be49077e54d5f/request-promise/request-promise.d.ts
declare module 'request-promise-native' {
  import request = require('request');
  import http = require('http');
  import errors = require('request-promise/errors');

  namespace requestPromise {
    interface RequestPromiseOptions extends request.CoreOptions {
      simple?: boolean;
      transform?: (body: any, response: http.IncomingMessage, resolveWithFullResponse?: boolean) => any;
      resolveWithFullResponse?: boolean;
    }

    export type OptionsWithUri = request.UriOptions & RequestPromiseOptions;
    export type OptionsWithUrl = request.UrlOptions & RequestPromiseOptions;
    export type Options = OptionsWithUri | OptionsWithUrl;
  }

  var requestPromise: request.RequestAPI<Promise<any> & request.Request, requestPromise.RequestPromiseOptions, request.RequiredUriUrl>;
  export = requestPromise;
}
